### PR TITLE
Update to Grafana 2.1.3

### PR DESCRIPTION
**Pull request by rafalyesware**
This updates Grafana to 2.1.3, which is the latest release.

As the original packaging, this includes both the source and binary .tar.gz's and the extracted binaries.

### CODE REVIEW

**Comment by eliperelman** [comment]
Bump.

**Comment by rafalyesware** [comment]
@eliperelman You might want to avoid 2.1.3 if you need to import dashboards from Graphite.  I've got a branch for 2.2.0-pre1 as well in my fork, which avoids that issue.

But it would be great if we could get one/both merged here :)

**Comment by rafalyesware** [comment]
See https://github.com/taskcluster/heroku-grafana/pull/2 for the 2.2.0-pre update.

**Comment by eliperelman** [comment]
@rafalyesware the teams that I am aware of using Grafana at Mozilla are using InfluxDB, so I think that should be OK.

@jonasfj @gregarndt anyone have time to take a look at this?

**Comment by jonasfj** [comment]
Sorry, I should have been watching this repo...

**Comment by jonasfj** [comment]
I landed the other one as 2.1.3 seemed worth skipping :)

@rafalyesware, if you want to help keeping this up-to-date let me know, I don't mind adding you as contributor...

**Comment by rafalyesware** [comment]
@jonasfj I've got a few folks here who've become quite fond of the enhancements in Grafana vs. raw Graphite, so I'd be happy to be in the loop.

**Pull request closed without merging**
