### PR TITLE
Add source tarball corresponding to the build.

### PR DESCRIPTION
**Pull request by rafalyesware**
This adds the source tarball I omitted from the previous build.  I'm going to wait until release plans for 2.5.x settle out until updating this further I think.

### CODE REVIEW

**Comment by rafalyesware** [comment]
@jonasfj Source tarball to complete the 2.2.0-pre1 upgrade.

**Comment by rafalyesware** [comment]
FWIW, we pushed our Grafana server built using this to production, so I will definitely be happy to help with maintenance.

**Comment by rafalyesware** [comment]
@jonasfj @gregarndt Ping

**Comment by jonasfj** [comment]
Oh, sorry I was out last week (still am)...

**Comment by jonasfj** [comment]
> FWIW, we pushed our Grafana server built using this to production, so I will definitely be happy to help with maintenance.

@rafalyesware,
Awesome... We're also auto-deploying from this repo... I've added you as member of a team that has read/write access to this repo... Feel free to merge PRs etc... and/or assign reviewers.
FYI, we hang out on irc.mozilla.org#taskcluster if you ever need to ping us... (hmm, I should probably configure my irc client to join #grafana one day)

Whilst it's not the end of the world, I guess we should strive to not break compatibility.

**Pull request merged**
