### PR TITLE
Update to Grafana 2.2.0pre1 (9/2/2015, 7:36:50 AM)

### PR DESCRIPTION
**Pull request by rafalyesware**
Update Grafana to the latest 2.2.0-prerelease build to pick up bugfix for https://github.com/grafana/grafana/issues/2490

### CODE REVIEW

**Comment by rafalyesware** [comment]
This is obviously a stopgap fix to address my issues with Graphite import being broken in 2.1.3; I'll update this to 2.2.0 release once that's available.

**Comment by jonasfj** [comment]
Well, let's land this... We probably ought to rename the folder to `grafana/` instead of doing `grafana-<version>/`.

Anyways, thanks for helping to keep this updated...

**Comment by rafalyesware** [comment]
@jonasfj Thanks!  Agreed on renaming, since the updates also always involve changing the path in `start.js` to match that directory.

I didn't push a source tarball here because it wasn't clear to be how to get the correct corresponding source distribution to the `pre1` build, but that also might be better to leave out since it's superfluous for those who are merely using this to push to Heroku.

**Comment by jonasfj** [comment]
@rafalyesware I include the source tarball for as a license compliance measure...

I'm not an on apache 2, but it seems like a safe measure :)

**Comment by rafalyesware** [comment]
Hmmm, good point.  I've opened an issue with Torkel requesting source artifacts for the builds as well (https://github.com/grafana/grafana/issues/2700).  In the meantime, I can open a pull with what appears to be the right vintage of build for `2.2.0-pre1`.

**Pull request merged**
